apiVersion : apps/v1
kind: Deployment
metadata:
  name: reco 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reco
  template:
    metadata:
      labels:
        app: reco 
    spec:
      containers:
        - name: reco 
          image: recoacr.azurecr.io/reco
          ports:
          - containerPort: 8501